version: 0.2

phases:

  install:
    runtime-versions:
      docker: 18

  # pre_build:
  #   commands:
  #     - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  #     - PATH=$PATH:$HOME/.cargo/bin

  build:
    commands:
      # - echo Building...
      # - cargo test
      # - cargo build --release
      # - echo Deploying infrastructure...
      # - chmod +x resources/setup.sh
      # Uncomment this command to create the user that the bucket sync needs in the commercial account
      # - aws cloudformation create-stack --stack-name bearcat-sync-user --template-body file://resources/bearcat-user.yml --capabilities "CAPABILITY_IAM" "CAPABILITY_NAMED_IAM"

      # Source bucket naming convention: <environment>-build-sync-bucket
      # Deployment bucket naming convention: <environment>-deploy-sync-bucket
      - aws cloudformation create-stack --stack-name bearcat-sync --template-body file://resources/bearcat.yaml --parameters ParameterKey=SourceBucketName,ParameterValue="cdc-build-sync-bucket-test" ParameterKey=DestinationBucketName,ParameterValue="devtest-deploy-sync-bucket" ParameterKey=KeyName,ParameterValue="cdc-bearcat-sync" ParameterKey=BuilderAccountId,ParameterValue="966799970081"
